version: "3.9"
services:
  db:
    container_name: lse-db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lse
      POSTGRES_PASSWORD: dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: lse_dev
    ports:
      - "5432:5432"
  web:
    container_name: lse-web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
    volumes:
      - .:/lse_app
    ports:
      - "3000:3000"
    depends_on:
      - db
